### PR TITLE
CoffeeScript -> JS

### PR DESCRIPTION
**Pull request by TimvdLippe**
This PR updates all coffeescript files to JS ES6 to be compatible with Hubot 3.

### CODE REVIEW

**Comment by MonicaG** [comment]
Thank you for the pull request! I will look at it and merge it or get back to you within the next day or so.

**Comment by MonicaG** [comment]
Hello @TimvdLippe 

Thank you for the PR.  Would you please update the [lmgtfy-test.coffee](https://github.com/MonicaG/hubot-lmgtfy/blob/master/test/lmgtfy-test.coffee) as part of this change.  

Thank you for updating this plugin!

Monica

**Comment by TimvdLippe** [comment]
@MonicaG Updated, thanks!

**Comment by MonicaG** [comment]
@TimvdLippe thanks for the update! I'll get the plugin put on npm by the end of this weekend.

**Comment by TimvdLippe** [comment]
@MonicaG Thanks a lot for the review and update on NPM!

**Pull request merged**
